### PR TITLE
add podman support (give --podman or -p argument to run with podman)

### PR DESCRIPTION
**Pull request by rojenzaman**
termux/termux-docker:podman branch can be applied from the podman branch I created. I can maintain it after import.

### CODE REVIEW

**Comment by Grimler91** [comment]
Cool! 

Maybe it would be better to have one subfolder for podman and one for docker, or to re-write the scripts to have some `--docker` and `--podman` argument for choosing between docker and podman?

Having two branches means that people might not find the podman branch unless they specifically look at which branches are available

**Comment by xeffyr** [comment]
Yes, better same branch.

Image name syntax `docker.io/xeffyr/termux:latest` seems valid for Docker too, tested with `run` and `build` commands. So you can simplify scripts to use syntax valid for both Docker and Podman.

**Comment by rojenzaman** [comment]
I think, It makes more sense to have a ln -s based (for system ) sub-folder for the podman, and easier to maintain.
I think the other way will lead to confusion.
what do you think?
Do I create a re-commit for the sub folder?

**Comment by rojenzaman** [comment]
> Yes, better same branch.
> 
> Image name syntax `docker.io/xeffyr/termux:latest` seems valid for Docker too, tested with `run` and `build` commands. So you can simplify scripts to use syntax valid for both Docker and Podman.

So let's alias the *podman* to *docker*. and script can check if podman-docker or docker and podman if exist on system.

**Comment by Grimler91** [comment]
> I think, It makes more sense to have a ln -s based (for system ) sub-folder for the podman, and easier to maintain.

Do we need two separate system folders? I guess everything in system can be identical for podman and docker?

> Do I create a re-commit for the sub folder?

You can squash and force-push onto your branch in this PR to update the PR

> So we can alias the docker to podman if podman exist on system.

People might have both docker and podman installed and want to use docker instead of podman (for whatever reason), from a user experience point of view it would be good with an option to choose between them. (podman can be default option though if found and user does not specify anything)

**Comment by rojenzaman** [comment]
>  People might have both docker and podman installed and want to use docker instead of podman (for whatever reason), from a user experience point of view it would be good with an option to choose between them. (podman can be default option though if found and user does not specify anything)

Okay, good idea. I will create now

**Comment by rojenzaman** [comment]
I did it as required, is there anything missing?

**Comment by rojenzaman** [comment]
tested under **ubuntu** and **fedora**

**Pull request merged**
